# Generated by Django 4.2.7 on 2024-01-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='userId',
            field=models.BigIntegerField(default=40),
            preserve_default=False,
        ),
    ]
