# Generated by Django 4.2.7 on 2024-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0002_remove_chatmessage_user_chatmessage_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat/media'),
        ),
    ]
