# Generated by Django 4.2.7 on 2024-01-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0003_chatmessage_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='chat/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='chat/video')),
            ],
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peerChat.media'),
        ),
    ]
