# Generated by Django 4.2.7 on 2024-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0004_media_alter_chatmessage_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
        migrations.AddField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat/media'),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
