# Generated by Django 4.2.7 on 2024-01-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0005_remove_media_image_remove_media_video_media_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='block_by_frst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='block_by_second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='hide_by_frst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='hide_by_second',
            field=models.BooleanField(default=False),
        ),
    ]
