# Generated by Django 4.2.7 on 2024-01-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0006_thread_block_by_frst_thread_block_by_second_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='block_by_frst',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='block_by_second',
        ),
        migrations.AddField(
            model_name='thread',
            name='block_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
