# Generated by Django 4.2.7 on 2024-01-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0007_remove_thread_block_by_frst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='reed',
            field=models.BooleanField(default=False),
        ),
    ]
