# Generated by Django 4.2.7 on 2024-01-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0008_thread_reed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='reed',
            field=models.BooleanField(default=True),
        ),
    ]
