# Generated by Django 4.2.7 on 2024-01-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerChat', '0011_thread_reed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='reed',
        ),
    ]
