# Generated by Django 4.2.7 on 2023-12-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoCalling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
