# Generated by Django 4.2.7 on 2024-01-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_document_user_document_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
