# Generated by Django 4.2.7 on 2023-11-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verifyed',
            field=models.BooleanField(default=False),
        ),
    ]
