# Generated by Django 4.2.7 on 2023-11-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifyed',
            new_name='is_verified',
        ),
    ]
