# Generated by Django 4.2.7 on 2024-01-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='premium',
        ),
    ]
